# Experiment 1 - Predict using XGBoost

### Notebook 2: Make Supervised suitable

**ToDo**
* Padronizar os data types
* Normalizar valores
* Pesquisar feature engineering para serie temporal multivariada
* Será que eu uso a feature tools? =P

In [8]:
import pandas as pd

In [17]:
data = pd.read_csv('../data/CMAPSSData/data_all.csv', parse_dates=['time'])
data.drop(['Unnamed: 0'], axis=1, inplace=True)

In [18]:
#sort by time
data = data.sort_values(by='time')

In [19]:
# criar os labels a partir de RUL
data['target'] = data['RUL'].apply(lambda x: 1 if x <=40 else 0)
data = data.drop(['RUL'], axis=1)
data.head(5)

,op_setting_1,op_setting_2,op_setting_3,sensor_meas_1,sensor_meas_2,sensor_meas_3,sensor_meas_4,sensor_meas_5,sensor_meas_6,sensor_meas_7,...,sensor_meas_20,sensor_meas_21,index,time,engine_no,time_in_cycles,sensor_meas_17,sensor_meas_18,engine_family,target
0,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,21.61,554.36,...,39.06,23.4190,0,2000-01-01 00:00:00,1.0,1.0,392.0,2388.0,1.0,0
20631,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,5.48,8.00,194.64,...,14.73,8.8071,0,2000-01-01 00:00:00,1.0,1.0,334.0,2223.0,2.0,1
74390,-0.0005,0.0004,100.0,518.67,642.36,1583.23,1396.84,14.62,21.61,553.97,...,39.11,23.3537,0,2000-01-01 00:00:00,1.0,1.0,391.0,2388.0,3.0,0
99110,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,5.70,137.36,...,10.62,6.3670,0,2000-01-01 00:00:00,1.0,1.0,330.0,2212.0,4.0,1
99111,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,13.61,332.10,...,24.37,14.6552,1,2000-01-01 00:10:00,1.0,2.0,361.0,2324.0,4.0,1

In [22]:
# Generate X and y
y = data['target']
X = data.drop(['target'], axis=1)

In [ ]:
# Persist